app:
  host: 127.0.0.1
  port: 8080
mysql:
  host: 172.16.160.12
  port: 3306
  database: go18
  username: "root"
  password: "123456"
  debug: true
log:
  level: "warn"
  rotate:
    filename: "../../logs/book.log"
    max_size: 1
    max_backups: 1
    max_age: 1
    compress: true
